music = {
    "Kesariya": "https://youtu.be/6mr4cYJ7yew",
    "Tum Hi Ho": "https://youtu.be/Umqb9KENgmk",
    "Channa Mereya": "https://youtu.be/bzSTpdcs-EI",
    "Agar Tum Saath Ho": "https://youtu.be/sK7riqg2mr4",
    "Phir Bhi Tumko Chaahunga": "https://www.youtube.com/results?search_query=Phir+Bhi+Tumko+Chaahunga+Arijit+Singh",
    "Chaleya": "https://www.youtube.com/results?search_query=Chaleya+Arijit+Singh",
    "Ve Kamleya": "https://www.youtube.com/results?search_query=Ve+Kamleya+Arijit+Singh",
    "Tera Yaar Hoon Main": "https://www.youtube.com/results?search_query=Tera+Yaar+Hoon+Main+Arijit+Singh",
    "Apna Bana Le": "https://www.youtube.com/results?search_query=Apna+Bana+Le+Arijit+Singh",
    "Sajni": "https://www.youtube.com/results?search_query=Sajni+Arijit+Singh",
    "Satranga": "https://www.youtube.com/results?search_query=Satranga+Arijit+Singh",
    "O Maahi": "https://www.youtube.com/results?search_query=O+Maahi+Arijit+Singh",
    "Aaj Se Teri": "https://www.youtube.com/results?search_query=Aaj+Se+Teri+Arijit+Singh",
    "Hawayein": "https://www.youtube.com/results?search_query=Hawayein+Arijit+Singh",
    "Samjhawan": "https://www.youtube.com/results?search_query=Samjhawan+Arijit+Singh",
    "Shayad": "https://www.youtube.com/results?search_query=Shayad+Arijit+Singh",
    "Pal": "https://www.youtube.com/results?search_query=Pal+Arijit+Singh",
    "Enna Sona": "https://www.youtube.com/results?search_query=Enna+Sona+Arijit+Singh",
    "Bandeya": "https://www.youtube.com/results?search_query=Bandeya+Arijit+Singh",
    "Ae Dil Hai Mushkil": "https://www.youtube.com/results?search_query=Ae+Dil+Hai+Mushkil+Arijit+Singh",
    "Kabira": "https://www.youtube.com/results?search_query=Kabira+Arijit+Singh",
    "Gerua": "https://www.youtube.com/results?search_query=Gerua+Arijit+Singh",
    "Khairiyat": "https://www.youtube.com/results?search_query=Khairiyat+Arijit+Singh",
    "Tujhe Kitna Chahne Lage": "https://www.youtube.com/results?search_query=Tujhe+Kitna+Chahne+Lage+Arijit+Singh",
    "Humdard": "https://www.youtube.com/results?search_query=Humdard+Arijit+Singh",
    "Muskurane": "https://www.youtube.com/results?search_query=Muskurane+Arijit+Singh",
    "Hamari Adhuri Kahani": "https://www.youtube.com/results?search_query=Hamari+Adhuri+Kahani+Arijit+Singh",
    "Aayat": "https://www.youtube.com/results?search_query=Aayat+Arijit+Singh",
    "Laal Ishq": "https://www.youtube.com/results?search_query=Laal+Ishq+Arijit+Singh",
    "Duaa": "https://www.youtube.com/results?search_query=Duaa+Arijit+Singh",
    "Phir Le Aaya Dil": "https://www.youtube.com/results?search_query=Phir+Le+Aaya+Dil+Arijit+Singh",
    "Aabaad Barbaad": "https://www.youtube.com/results?search_query=Aabaad+Barbaad+Arijit+Singh",
    "Aahista": "https://www.youtube.com/results?search_query=Aahista+Arijit+Singh",
    "Aashiqui Aa Gayi": "https://www.youtube.com/results?search_query=Aashiqui+Aa+Gayi+Arijit+Singh",
    "Bairiya": "https://www.youtube.com/results?search_query=Bairiya+Arijit+Singh",
    "Heeriye": "https://www.youtube.com/results?search_query=Heeriye+Arijit+Singh",

    "Mere Sapno Ki Rani": "https://youtu.be/9PdSmDRGIwM",
    "Roop Tera Mastana": "https://youtu.be/dyEdcOhxJNQ",
    "Pal Pal Dil Ke Paas": "https://youtu.be/AMuRRXCuy-4",
    "Mere Samne Wali Khidki Mein": "https://www.youtube.com/results?search_query=Mere+Samne+Wali+Khidki+Mein+Kishore+Kumar",
    "O Mere Dil Ke Chain": "https://www.youtube.com/results?search_query=O+Mere+Dil+Ke+Chain+Kishore+Kumar",
    "Neele Neele Ambar Par": "https://www.youtube.com/results?search_query=Neele+Neele+Ambar+Par+Kishore+Kumar",
    "Khaike Paan Banaraswala": "https://www.youtube.com/results?search_query=Khaike+Paan+Banaraswala+Kishore+Kumar",
    "Zindagi Ek Safar Hai Suhana": "https://www.youtube.com/results?search_query=Zindagi+Ek+Safar+Hai+Suhana+Kishore+Kumar",
    "Yeh Shaam Mastani": "https://www.youtube.com/results?search_query=Yeh+Shaam+Mastani+Kishore+Kumar",
    "Yeh Jo Mohabbat Hai": "https://www.youtube.com/results?search_query=Yeh+Jo+Mohabbat+Hai+Kishore+Kumar",
    "Ek Ajnabee Haseena Se": "https://www.youtube.com/results?search_query=Ek+Ajnabee+Haseena+Se+Kishore+Kumar",
    "O Saathi Re": "https://www.youtube.com/results?search_query=O+Saathi+Re+Kishore+Kumar",
    "Agar Tum Na Hote": "https://www.youtube.com/results?search_query=Agar+Tum+Na+Hote+Kishore+Kumar",
    "Humein Tumse Pyaar Kitna": "https://www.youtube.com/results?search_query=Humein+Tumse+Pyaar+Kitna+Kishore+Kumar",
    "Aap Ki Aankhon Mein Kuch": "https://www.youtube.com/results?search_query=Aap+Ki+Aankhon+Mein+Kuch+Kishore+Kumar",
    "Tere Bina Zindagi Se": "https://www.youtube.com/results?search_query=Tere+Bina+Zindagi+Se+Kishore+Kumar",
    "Musafir Hoon Yaaron": "https://www.youtube.com/results?search_query=Musafir+Hoon+Yaaron+Kishore+Kumar",
    "Kuchh To Log Kahenge": "https://www.youtube.com/results?search_query=Kuchh+To+Log+Kahenge+Kishore+Kumar",
    "Rimjhim Gire Saawan": "https://www.youtube.com/results?search_query=Rimjhim+Gire+Saawan+Kishore+Kumar",
    "Aanewala Pal Janewala Hai": "https://www.youtube.com/results?search_query=Aanewala+Pal+Janewala+Hai+Kishore+Kumar",
    "O Mere Sona Re": "https://www.youtube.com/results?search_query=O+Mere+Sona+Re+Kishore+Kumar",
    "Pyar Deewana Hota Hai": "https://youtu.be/wtfRQ76-I7k?si=ptGIsfAnY8_uQvIi",
    "Chookar Mere Man Ko": "https://www.youtube.com/results?search_query=Chookar+Mere+Man+Ko+Kishore+Kumar",
    "Jab Koi Baat Bigad Jaye": "https://www.youtube.com/results?search_query=Jab+Koi+Baat+Bigad+Jaye+Kishore+Kumar",
    "Gaata Rahe Mera Dil": "https://www.youtube.com/results?search_query=Gaata+Rahe+Mera+Dil+Kishore+Kumar",
    "Khaabon Ke Parinday": "https://www.youtube.com/results?search_query=Khaabon+Ke+Parinday+Kishore+Kumar"
}